# Generated by Django 3.1.4 on 2021-01-14 21:10

import uuid

from django.db import migrations, models


def create_uuid(apps, schema_editor):
    TPost = apps.get_model("post", "TPost")
    for t_post in TPost.objects.all():
        t_post.uuid = uuid.uuid4()
        t_post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_tpost_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="tpost",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="tpost",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
