# Generated by Django 3.1.4 on 2021-01-23 21:03

from django.db import migrations


def set_published_date(apps, schema_editor):
    TPost = apps.get_model("post", "TPost")
    for t_post in TPost.objects.all():
        if t_post.m_post_status.key == "published":
            t_post.published = t_post.created_at
        t_post.updated = t_post.updated_at
        t_post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_tpost_uuid"),
    ]

    operations = [
        migrations.RunPython(set_published_date),
        migrations.RenameField(
            model_name="tpost",
            old_name="published",
            new_name="dt_published",
        ),
        migrations.RenameField(
            model_name="tpost",
            old_name="updated",
            new_name="dt_updated",
        ),
    ]
