# Generated by Django 3.2.2 on 2021-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
        ("post", "0008_tpost_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="tpost",
            name="trips",
            field=models.ManyToManyField(through="trips.TTripPost", to="trips.TTrip"),
        ),
    ]
