# Generated by Django 5.2.14 on 2026-05-24 11:39

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_alter_tfile_posts"),
        ("post", "0009_tpost_trips"),
        ("streams", "0004_update_verbose_names"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="tpost",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="tpost",
            name="files",
            field=models.ManyToManyField(
                through="files.TFilePost", through_fields=("t_post", "t_file"), to="files.tfile"
            ),
        ),
        migrations.AlterField(
            model_name="tpost",
            name="streams",
            field=models.ManyToManyField(
                through="streams.TStreamPost", through_fields=("t_post", "m_stream"), to="streams.mstream"
            ),
        ),
    ]
