# Generated by Django 3.1.4 on 2021-02-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0003_tokenproxy"),
        ("indieweb", "0002_twebmentionsend"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMicropubScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "m_micropub_scope",
            },
        ),
        migrations.CreateModel(
            name="TToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.URLField()),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authtoken.token",
                    ),
                ),
            ],
            options={
                "db_table": "t_token",
            },
        ),
        migrations.CreateModel(
            name="TTokenMicropubScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "m_micropub_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indieweb.mmicropubscope",
                    ),
                ),
                (
                    "t_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indieweb.ttoken",
                    ),
                ),
            ],
            options={
                "db_table": "t_token_micropub_scope",
                "unique_together": {("t_token", "m_micropub_scope")},
            },
        ),
    ]
