# Generated by Django 3.1.4 on 2021-02-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0003_tokenproxy"),
        ("indieweb", "0004_register_m_micropub_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttoken",
            name="micropub_scope",
            field=models.ManyToManyField(
                through="indieweb.TTokenMicropubScope", to="indieweb.MMicropubScope"
            ),
        ),
        migrations.AlterField(
            model_name="ttoken",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t_token",
                to="authtoken.token",
            ),
        ),
    ]
