# Generated by Django 3.2.2 on 2021-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indieweb", "0004_add_default_scopes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mmicropubscope",
            options={"verbose_name": "Micropub Scope", "verbose_name_plural": "Micropub Scopes"},
        ),
        migrations.AlterModelOptions(
            name="ttoken",
            options={"verbose_name": "Token", "verbose_name_plural": "Tokens"},
        ),
        migrations.AlterModelOptions(
            name="ttokenmicropubscope",
            options={"verbose_name": "Token-Micropub Scope"},
        ),
        migrations.AlterModelOptions(
            name="twebmention",
            options={"verbose_name": "Webmention Approval", "verbose_name_plural": "Webmention Approvals"},
        ),
        migrations.AlterModelOptions(
            name="twebmentionsend",
            options={"verbose_name": "Sent Webmention", "verbose_name_plural": "Sent Webmentions"},
        ),
    ]
