# Generated by Django 5.2.14 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_update_verbose_names"),
        ("post", "0009_tpost_trips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfile",
            name="posts",
            field=models.ManyToManyField(
                through="files.TFilePost", through_fields=("t_file", "t_post"), to="post.tpost"
            ),
        ),
    ]
