# Generated by Django 4.2.7 on 2023-11-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0008_fix_location_coordinates"),
    ]

    operations = [
        migrations.CreateModel(
            name="BridgyPublishUrl",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bridgy_publish_url",
                        to="entry.tentry",
                    ),
                ),
            ],
            options={
                "unique_together": {("entry", "url")},
            },
        ),
    ]
