# Generated by Django 3.2.16 on 2022-12-26 23:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("vendor_id", models.CharField(max_length=255, unique=True)),
                ("upload_id", models.CharField(max_length=255, null=True, unique=True)),
                ("distance", models.FloatField(help_text="Distance in meters", null=True)),
                ("moving_time", models.PositiveIntegerField(help_text="Moving time in seconds")),
                ("elapsed_time", models.PositiveIntegerField(help_text="Moving time in seconds")),
                ("total_elevation_gain", models.FloatField()),
                ("elevation_high", models.FloatField()),
                ("elevation_low", models.FloatField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("AlpineSki", "Alpine Ski"),
                            ("BackcountrySki", "Back Country Ski"),
                            ("Canoeing", "Canoeing"),
                            ("Crossfit", "Crossfit"),
                            ("EBikeRide", "E Bike Ride"),
                            ("Elliptical", "Elliptical"),
                            ("EMountainBikeRide", "E Mountain Bike Ride"),
                            ("Golf", "Golf"),
                            ("GravelRide", "Gravel Ride"),
                            ("Handcycle", "Handcycle"),
                            ("Hike", "Hike"),
                            ("IceSkate", "Ice Skate"),
                            ("InlineSkate", "Inline Skate"),
                            ("Kayaking", "Kayakingkayaking"),
                            ("Kitesurf", "Kitesurf"),
                            ("MountainBikeRide", "Mountain Bike Ride"),
                            ("NordicSki", "Nordic Ski"),
                            ("Ride", "Ride"),
                            ("RockClimbing", "Rock Climbing"),
                            ("RollerSki", "Roller Ski"),
                            ("Rowing", "Rowing"),
                            ("Run", "Run"),
                            ("sail", "Sail"),
                            ("skateboard", "Skateboard"),
                            ("snowboard", "Snowboard"),
                            ("snowshoe", "Snowshoe"),
                            ("Soccer", "Soccer"),
                            ("StairStepper", "Stair Stepper"),
                            ("StandUpPaddling", "Stand Up Paddling"),
                            ("Surfing", "Surfing"),
                            ("Swim", "Swim"),
                            ("TrailRun", "Trail Run"),
                            ("Velomobile", "Velomobile"),
                            ("VirtualRide", "Virtual Ride"),
                            ("VirtualRun", "Virtual Run"),
                            ("Walk", "Walk"),
                            ("WeightTraining", "Weight Training"),
                            ("Wheelchair", "Wheelchair"),
                            ("Windsurf", "Windsurf"),
                            ("Workout", "Workout"),
                            ("Yoga", "Yoga"),
                        ],
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("start_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=3857)),
                ("end_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=3857)),
                ("average_speed", models.FloatField(help_text="Average speed in meters per second")),
                ("max_speed", models.FloatField()),
                ("average_heartrate", models.FloatField(null=True)),
                ("max_heartrate", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary_polyline", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="exercise.activity")),
            ],
        ),
        migrations.CreateModel(
            name="GPXRoute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="exercise.activity")),
            ],
        ),
    ]
