# Generated by Django 3.2.16 on 2022-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_accesstoken_athlete_refreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="vendor_id",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
