# Generated by Django 4.2 on 2023-07-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0008_fix_location_coordinates"),
        ("exercise", "0003_map_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="entry",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="entry.tentry", related_name="activities"
            ),
        ),
    ]
