# Generated by Django 4.2 on 2023-07-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_update_verbose_names"),
        ("exercise", "0004_activity_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor_id", models.CharField(max_length=128, unique=True)),
                ("params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="exercise.activity"
                    ),
                ),
                ("t_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.tfile")),
            ],
        ),
    ]
