# Generated by Django 4.2.5 on 2023-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0005_activityphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="svg",
            field=models.TextField(default=""),
        ),
    ]
