# Generated by Django 3.2.2 on 2021-07-04 21:16

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_update_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'Everyone'), (2, 'Only me'), (3, 'People who know the url')], default=core.constants.Visibility['PUBLIC']),
        ),
    ]
