# Generated by Django 3.2.12 on 2022-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttrip",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ttriplocation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ttrippost",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
