# Generated by Django 3.2.2 on 2021-06-03 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msitesettings",
            options={"verbose_name": "Site Settings", "verbose_name_plural": "Site Settings"},
        ),
    ]
