# Generated by Django 3.2.2 on 2022-01-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_msitesettings_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="msitesettings",
            name="footer_snippet",
            field=models.TextField(
                blank=True,
                default='<div class="text-center"><span class="help-text">Powered by <a href="http://tanzawa.blog"><span class="mr-1">🏔</span>Tanzawa</a></span></div>',
                help_text="Add an html snippet that will appear in the footer of your site.",
            ),
        ),
        migrations.AddField(
            model_name="msitesettings",
            name="icon",
            field=models.CharField(blank=True, default="🏔", max_length=2),
        ),
    ]
