# Generated by Django 3.2.2 on 2021-11-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0005_update_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="TNow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="", help_text="What are you focusing on _now_?")),
            ],
            options={
                "verbose_name": "Now",
                "verbose_name_plural": "Now",
            },
        ),
        migrations.CreateModel(
            name="TFileNow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("t_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.tfile")),
                ("t_now", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="now.tnow")),
            ],
            options={
                "verbose_name": "File-Now",
                "verbose_name_plural": "File-Now",
            },
        ),
    ]
