# Generated by Django 3.2.2 on 2021-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_update_verbose_names"),
        ("now", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tnow",
            name="files",
            field=models.ManyToManyField(through="now.TFileNow", to="files.TFile"),
        ),
    ]
