# Generated by Django 3.1.4 on 2021-03-25 21:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

import data.wordpress.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0003_tfile_exif"),
        ("post", "0006_tpost_streams"),
        ("streams", "0002_add_default_streams"),
    ]

    operations = [
        migrations.CreateModel(
            name="TWordpress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_file",
                    models.FileField(upload_to=data.wordpress.upload.wordpress_upload_to),
                ),
                ("filename", models.CharField(max_length=128)),
                ("link", models.URLField()),
                ("base_site_url", models.URLField()),
                ("base_blog_url", models.URLField()),
            ],
            options={
                "db_table": "t_wordpress",
            },
        ),
        migrations.CreateModel(
            name="TWordpressPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.CharField(max_length=256)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "t_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.tpost",
                    ),
                ),
                (
                    "t_wordpress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_wordpress_post",
                        to="wordpress.twordpress",
                    ),
                ),
            ],
            options={
                "db_table": "t_wordpress_post",
            },
        ),
        migrations.CreateModel(
            name="TWordpressAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.CharField(max_length=256)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "t_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.tfile",
                    ),
                ),
                (
                    "t_wordpress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_wordpress_attachment",
                        to="wordpress.twordpress",
                    ),
                ),
            ],
            options={
                "db_table": "t_wordpress_attachment",
            },
        ),
        migrations.CreateModel(
            name="TPostKind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("nice_name", models.SlugField(max_length=64)),
                (
                    "m_post_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_post_kind",
                        to="post.mpostkind",
                    ),
                ),
                (
                    "t_wordpress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_post_kind",
                        to="wordpress.twordpress",
                    ),
                ),
            ],
            options={
                "db_table": "t_wordpress_post_kind",
            },
        ),
        migrations.CreateModel(
            name="TPostFormat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("nice_name", models.SlugField(max_length=64)),
                (
                    "m_post_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_post_format",
                        to="post.mpostkind",
                    ),
                ),
                (
                    "t_wordpress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_post_format",
                        to="wordpress.twordpress",
                    ),
                ),
            ],
            options={
                "db_table": "t_wordpress_post_format",
            },
        ),
        migrations.CreateModel(
            name="TCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("nice_name", models.SlugField(max_length=64)),
                (
                    "m_stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streams.mstream",
                    ),
                ),
                (
                    "t_wordpress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_category",
                        to="wordpress.twordpress",
                    ),
                ),
            ],
            options={
                "db_table": "t_wordpress_category",
            },
        ),
    ]
