# Generated by Django 3.1.4 on 2021-04-03 21:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="twordpresspost",
            name="path",
            field=models.CharField(db_index=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="twordpresspost",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
