# Generated by Django 3.1.4 on 2021-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordpress", "0002_add_twordpresspost_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="twordpressattachment",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
