# Generated by Django 3.1.4 on 2021-05-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_tfile_exif"),
        ("post", "0006_tpost_streams"),
        ("wordpress", "0003_twordpressattachment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tpostformat",
            name="m_post_kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ref_t_post_format",
                to="post.mpostkind",
            ),
        ),
        migrations.AlterField(
            model_name="tpostkind",
            name="m_post_kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ref_t_post_kind",
                to="post.mpostkind",
            ),
        ),
        migrations.AlterField(
            model_name="twordpressattachment",
            name="t_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.tfile",
            ),
        ),
    ]
