# Generated by Django 3.2.2 on 2022-01-15 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("indieweb", "0005_update_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="TRelMe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.URLField(
                        help_text="URL to your profile on other sites. Email adddress should start with mailto.",
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="relme", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Relme",
                "verbose_name_plural": "Relme",
                "db_table": "t_rel_me",
            },
        ),
    ]
