# Generated by Django 3.2.2 on 2022-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0006_trelme"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttoken",
            name="exchanged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
