# Generated by Django 4.2.7 on 2023-11-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0007_ttoken_exchanged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="twebmentionsend",
            name="response_body",
            field=models.JSONField(default=dict),
        ),
    ]
