# Generated by Django 5.2.14 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indieweb", "0008_twebmentionsend_response_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttoken",
            name="micropub_scope",
            field=models.ManyToManyField(
                through="indieweb.TTokenMicropubScope",
                through_fields=("t_token", "m_micropub_scope"),
                to="indieweb.mmicropubscope",
            ),
        ),
    ]
