# Generated by Django 3.1.4 on 2021-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Tanzawa', max_length=128, blank=True)),
                ('subtitle', models.CharField(default='', max_length=128, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
