# Generated by Django 3.2.2 on 2021-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msitesettings',
            name='footer_snippet',
            field=models.TextField(blank=True, default='<span class="help-text">Powered by <a href="http://tanzawa.blog"><span class="mr-1">🏔</span>Tanzawa</a></span>', help_text='Add an html snippet that will appear in the footer of your site.'),
        ),
    ]
