# Generated by Django 3.2.2 on 2022-01-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_update_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="msitesettings",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
