# Generated by Django 3.1.4 on 2021-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0002_add_default_streams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mstream",
            name="icon",
            field=models.CharField(help_text="Select an emoji", max_length=2),
        ),
    ]
