# Generated by Django 3.1.4 on 2021-01-29 07:35

import django.db.models.deletion
import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webmention", "0001_initial"),
        ("post", "0005_rename_published_updated_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="TWebmention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approval_status", models.BooleanField(blank=True, null=True)),
                (
                    "microformat_data",
                    picklefield.fields.PickledObjectField(editable=False),
                ),
                (
                    "t_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_webmention",
                        to="post.tpost",
                    ),
                ),
                (
                    "t_webmention_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_t_webmention",
                        to="webmention.webmentionresponse",
                    ),
                ),
            ],
            options={
                "db_table": "t_webmention",
                "unique_together": {("t_webmention_response", "t_post")},
            },
        ),
    ]
