# Generated by Django 3.2.2 on 2021-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0002_add_default_streams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mstream",
            name="icon",
            field=models.CharField(help_text="Select an emoji", max_length=2),
        ),
    ]
