# Generated by Django 3.2.2 on 2021-06-03 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0003_alter_mstream_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mstream",
            options={"verbose_name": "Stream", "verbose_name_plural": "Streams"},
        ),
        migrations.AlterModelOptions(
            name="tstreampost",
            options={"verbose_name": "Stream-Post", "verbose_name_plural": "Stream-Posts"},
        ),
    ]
