# Generated by Django 5.2.14 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_tpost_tags_alter_tpost_files_alter_tpost_streams"),
        ("streams", "0004_update_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mstream",
            name="posts",
            field=models.ManyToManyField(
                through="streams.TStreamPost", through_fields=("m_stream", "t_post"), to="post.tpost"
            ),
        ),
    ]
