# Generated by Django 3.2.13 on 2022-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measurement",
                    models.CharField(
                        choices=[("positive", "Positive"), ("neutral", "Neutral"), ("negative", "Negative")],
                        max_length=12,
                    ),
                ),
                ("measured_at", models.DateTimeField(unique_for_date=True)),
            ],
            options={
                "verbose_name": "Mood",
                "verbose_name_plural": "Mood",
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measurement", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "unit",
                    models.CharField(choices=[("kg", "Kilograms"), ("lbs", "Pounds")], default="kg", max_length=3),
                ),
                ("measured_at", models.DateTimeField(unique_for_date=True)),
            ],
            options={
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
    ]
