# Generated by Django 3.1.4 on 2020-12-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p_name', models.CharField(max_length=255)),
                ('p_summary', models.CharField(blank=True, default='', max_length=1024)),
                ('e_content', models.TextField(blank=True, default='')),
                ('t_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.tpost')),
            ],
            options={
                'db_table': 't_entry',
            },
        ),
    ]
