# Generated by Django 3.1.4 on 2021-03-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0004_tcheckin_tlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TSyndication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "t_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_syndication",
                        to="entry.tentry",
                    ),
                ),
            ],
            options={
                "db_table": "t_syndication",
                "unique_together": {("t_entry", "url")},
            },
        ),
    ]
