# Generated by Django 3.2.2 on 2021-06-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_tpost_streams"),
        ("entry", "0005_tsyndication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tentry",
            name="t_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="ref_t_entry", to="post.tpost"
            ),
        ),
    ]
