# Generated by Django 3.1.4 on 2021-05-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_tfile_exif'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tformattedimage',
            unique_together={('t_file', 'mime_type', 'width', 'height')},
        ),
    ]
